package com.demo.overcooked.ui.transporter.ingredients;

import com.demo.overcooked.ui.Constants;
import javax.swing.ImageIcon;

public class cheese extends javax.swing.JPanel {

    Constants constant = new Constants();

    public cheese() {
        initComponents();
        this.setOpaque(false);
        this.setName(constant.INGREDIENT_CHEESE);

        ImageIcon image = new ImageIcon("assets/ingredients/cheese.png");
        background.setIcon(image);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 120));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    // End of variables declaration//GEN-END:variables
}
