package com.demo.overcooked.ui.transporter.ingredients;

import com.demo.overcooked.ui.Constants;
import javax.swing.ImageIcon;


public class meat extends javax.swing.JPanel {

    Constants constant = new Constants();

  
    public meat() {
        initComponents();
        this.setOpaque(false);
        this.setName(constant.INGREDIENT_MEAT);
        
        ImageIcon image = new ImageIcon("assets/ingredients/meat.png");
        background.setIcon(image);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addIngredient = new javax.swing.JButton();
        deleteIngredient = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(addIngredient, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 70, 50));
        add(deleteIngredient, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 60, 50));
        add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 120));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addIngredient;
    private javax.swing.JLabel background;
    private javax.swing.JButton deleteIngredient;
    // End of variables declaration//GEN-END:variables
}
