/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.demo.overcooked.ui;

import com.demo.overcooked.estructuras.ordenes.*;
import com.demo.overcooked.ui.orders.tiny.*;
import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.io.InputStream;
import java.util.Random;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

/**
 *
 * @author Puta'
 */
public class GameScreenUI extends javax.swing.JFrame {

    private static GameScreenUI instance;

    private GameScreenUI() {
        initComponents();
        this.setLocationRelativeTo(this);
        ImageIcon image = new ImageIcon("assets/backgrounds/GameScreen1.png");
        background.setIcon(image);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        orderOnePanel = new javax.swing.JPanel();
        orderTwoPanel = new javax.swing.JPanel();
        orderThreePanel = new javax.swing.JPanel();
        mainOrderPanel = new javax.swing.JPanel();
        gameTimerLabel = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout orderOnePanelLayout = new javax.swing.GroupLayout(orderOnePanel);
        orderOnePanel.setLayout(orderOnePanelLayout);
        orderOnePanelLayout.setHorizontalGroup(
            orderOnePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        orderOnePanelLayout.setVerticalGroup(
            orderOnePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );

        getContentPane().add(orderOnePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 200, 160));

        javax.swing.GroupLayout orderTwoPanelLayout = new javax.swing.GroupLayout(orderTwoPanel);
        orderTwoPanel.setLayout(orderTwoPanelLayout);
        orderTwoPanelLayout.setHorizontalGroup(
            orderTwoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        orderTwoPanelLayout.setVerticalGroup(
            orderTwoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );

        getContentPane().add(orderTwoPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 200, 160));

        javax.swing.GroupLayout orderThreePanelLayout = new javax.swing.GroupLayout(orderThreePanel);
        orderThreePanel.setLayout(orderThreePanelLayout);
        orderThreePanelLayout.setHorizontalGroup(
            orderThreePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        orderThreePanelLayout.setVerticalGroup(
            orderThreePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );

        getContentPane().add(orderThreePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 540, 200, 160));

        javax.swing.GroupLayout mainOrderPanelLayout = new javax.swing.GroupLayout(mainOrderPanel);
        mainOrderPanel.setLayout(mainOrderPanelLayout);
        mainOrderPanelLayout.setHorizontalGroup(
            mainOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
        );
        mainOrderPanelLayout.setVerticalGroup(
            mainOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );

        getContentPane().add(mainOrderPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(395, 190, 610, 320));

        gameTimerLabel.setFont(new java.awt.Font("Poppins Black", 0, 24)); // NOI18N
        gameTimerLabel.setForeground(new java.awt.Color(158, 176, 158));
        gameTimerLabel.setText("00:00");
        gameTimerLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(gameTimerLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 30, 80, 50));
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1360, 760));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameScreenUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameScreenUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameScreenUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameScreenUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameScreenUI().setVisible(true);
            }
        });
    }

    public JLabel getTimerLabel() {
        return gameTimerLabel;
    }

    public JPanel getMainOrderPanel() {
        return mainOrderPanel;
    }

    public JPanel getOrderOnePanel() {
        return orderOnePanel;
    }

    public JPanel getOrderThreePanel() {
        return orderThreePanel;
    }

    public JPanel getOrderTwoPanel() {
        return orderTwoPanel;
    }

    public static GameScreenUI getInstance() {
        if (instance == null) {
            instance = new GameScreenUI();
        }
        return instance;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel gameTimerLabel;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JPanel mainOrderPanel;
    private javax.swing.JPanel orderOnePanel;
    private javax.swing.JPanel orderThreePanel;
    private javax.swing.JPanel orderTwoPanel;
    // End of variables declaration//GEN-END:variables
}
