package com.demo.overcooked.ui;


import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;




public class GameScreenUI extends javax.swing.JFrame {

    private static GameScreenUI instance;
    File file = new File("assets/Sounds/SoundtrackInGame.wav");
    static Clip gameWAV;

    private GameScreenUI() {
        initComponents();
        this.setLocationRelativeTo(this);
        ImageIcon image = new ImageIcon("assets/backgrounds/GameScreen1.png");
        background.setIcon(image);
        reproducir(file);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        gameTimerLabel = new javax.swing.JLabel();
        gamePointsLabel = new javax.swing.JLabel();
        orderOnePanel = new javax.swing.JPanel();
        orderTwoPanel = new javax.swing.JPanel();
        orderThreePanel = new javax.swing.JPanel();
        mainOrderPanel = new javax.swing.JPanel();
        transporterPanelOne = new javax.swing.JPanel();
        transporterPanelTwo = new javax.swing.JPanel();
        transporterPanelThree = new javax.swing.JPanel();
        transporterPanelFour = new javax.swing.JPanel();
        transporterPanelFive = new javax.swing.JPanel();
        background = new javax.swing.JLabel();

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        gameTimerLabel.setFont(new java.awt.Font("Poppins Black", 0, 24)); // NOI18N
        gameTimerLabel.setForeground(new java.awt.Color(158, 176, 158));
        gameTimerLabel.setText("00:00");
        gameTimerLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(gameTimerLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 40, 80, 30));

        gamePointsLabel.setFont(new java.awt.Font("Poppins Black", 0, 24)); // NOI18N
        gamePointsLabel.setForeground(new java.awt.Color(158, 176, 158));
        gamePointsLabel.setText("0pts");
        gamePointsLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(gamePointsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 40, 80, 30));

        javax.swing.GroupLayout orderOnePanelLayout = new javax.swing.GroupLayout(orderOnePanel);
        orderOnePanel.setLayout(orderOnePanelLayout);
        orderOnePanelLayout.setHorizontalGroup(
            orderOnePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        orderOnePanelLayout.setVerticalGroup(
            orderOnePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );

        getContentPane().add(orderOnePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 200, 160));

        javax.swing.GroupLayout orderTwoPanelLayout = new javax.swing.GroupLayout(orderTwoPanel);
        orderTwoPanel.setLayout(orderTwoPanelLayout);
        orderTwoPanelLayout.setHorizontalGroup(
            orderTwoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        orderTwoPanelLayout.setVerticalGroup(
            orderTwoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );

        getContentPane().add(orderTwoPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 200, 160));

        javax.swing.GroupLayout orderThreePanelLayout = new javax.swing.GroupLayout(orderThreePanel);
        orderThreePanel.setLayout(orderThreePanelLayout);
        orderThreePanelLayout.setHorizontalGroup(
            orderThreePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        orderThreePanelLayout.setVerticalGroup(
            orderThreePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );

        getContentPane().add(orderThreePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 540, 200, 160));

        javax.swing.GroupLayout mainOrderPanelLayout = new javax.swing.GroupLayout(mainOrderPanel);
        mainOrderPanel.setLayout(mainOrderPanelLayout);
        mainOrderPanelLayout.setHorizontalGroup(
            mainOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
        );
        mainOrderPanelLayout.setVerticalGroup(
            mainOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );

        getContentPane().add(mainOrderPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 180, 610, 320));

        javax.swing.GroupLayout transporterPanelOneLayout = new javax.swing.GroupLayout(transporterPanelOne);
        transporterPanelOne.setLayout(transporterPanelOneLayout);
        transporterPanelOneLayout.setHorizontalGroup(
            transporterPanelOneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );
        transporterPanelOneLayout.setVerticalGroup(
            transporterPanelOneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        getContentPane().add(transporterPanelOne, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 530, 170, 200));
        transporterPanelOne.setName("transporter-panel-one");

        javax.swing.GroupLayout transporterPanelTwoLayout = new javax.swing.GroupLayout(transporterPanelTwo);
        transporterPanelTwo.setLayout(transporterPanelTwoLayout);
        transporterPanelTwoLayout.setHorizontalGroup(
            transporterPanelTwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );
        transporterPanelTwoLayout.setVerticalGroup(
            transporterPanelTwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        getContentPane().add(transporterPanelTwo, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 530, 160, 200));
        transporterPanelTwo.setName("transporter-panel-two");

        javax.swing.GroupLayout transporterPanelThreeLayout = new javax.swing.GroupLayout(transporterPanelThree);
        transporterPanelThree.setLayout(transporterPanelThreeLayout);
        transporterPanelThreeLayout.setHorizontalGroup(
            transporterPanelThreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );
        transporterPanelThreeLayout.setVerticalGroup(
            transporterPanelThreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        getContentPane().add(transporterPanelThree, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 530, 170, 200));
        transporterPanelThree.setName("transporter-panel-three");

        javax.swing.GroupLayout transporterPanelFourLayout = new javax.swing.GroupLayout(transporterPanelFour);
        transporterPanelFour.setLayout(transporterPanelFourLayout);
        transporterPanelFourLayout.setHorizontalGroup(
            transporterPanelFourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );
        transporterPanelFourLayout.setVerticalGroup(
            transporterPanelFourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        getContentPane().add(transporterPanelFour, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 530, 170, 200));
        transporterPanelFour.setName("transporter-panel-four");

        javax.swing.GroupLayout transporterPanelFiveLayout = new javax.swing.GroupLayout(transporterPanelFive);
        transporterPanelFive.setLayout(transporterPanelFiveLayout);
        transporterPanelFiveLayout.setHorizontalGroup(
            transporterPanelFiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );
        transporterPanelFiveLayout.setVerticalGroup(
            transporterPanelFiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        getContentPane().add(transporterPanelFive, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 530, 170, 200));
        transporterPanelFive.setName("transporter-panel-five");
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1360, 760));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameScreenUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameScreenUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameScreenUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameScreenUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameScreenUI().setVisible(true);
            }
        });
    }

    public JLabel getTimerLabel() {
        return gameTimerLabel;
    }
    
    public JLabel getPointsLabel() {
        return gamePointsLabel;
    }

    public JPanel getMainOrderPanel() {
        return mainOrderPanel;
    }

    public JPanel getOrderOnePanel() {
        return orderOnePanel;
    }

    public JPanel getOrderThreePanel() {
        return orderThreePanel;
    }

    public JPanel getOrderTwoPanel() {
        return orderTwoPanel;
    }

    public JPanel getTransporterPanelFive() {
        return transporterPanelFive;
    }

    public JPanel getTransporterPanelFour() {
        return transporterPanelFour;
    }

    public JPanel getTransporterPanelOne() {
        return transporterPanelOne;
    }

    public JPanel getTransporterPanelThree() {
        return transporterPanelThree;
    }

    public JPanel getTransporterPanelTwo() {
        return transporterPanelTwo;
    }

    
    
    public static GameScreenUI getInstance() {
        if (instance == null) {
            instance = new GameScreenUI();
        }
        return instance;
    }
    
      public static void SetIntroWAV(Clip clip) {
        gameWAV = clip;
    }

    public static void reproducir(File file) {
        try {
            Clip sound = AudioSystem.getClip();
            sound.open(AudioSystem.getAudioInputStream(file));
            SetIntroWAV(sound);
            sound.start();

        } catch (Exception e) {
            System.out.println(e);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel gamePointsLabel;
    private javax.swing.JLabel gameTimerLabel;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JPanel mainOrderPanel;
    private javax.swing.JPanel orderOnePanel;
    private javax.swing.JPanel orderThreePanel;
    private javax.swing.JPanel orderTwoPanel;
    private javax.swing.JPanel transporterPanelFive;
    private javax.swing.JPanel transporterPanelFour;
    private javax.swing.JPanel transporterPanelOne;
    private javax.swing.JPanel transporterPanelThree;
    private javax.swing.JPanel transporterPanelTwo;
    // End of variables declaration//GEN-END:variables
}
